language: ruby
sudo: false
cache: bundler

before_install:
  - cd doorkeeper && git checkout v${doorkeeper}

script:
  - bundle exec rake

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1

env:
  - rails=3.2.0 doorkeeper=3.0.0
  - rails=4.1.0 doorkeeper=3.0.0
  - rails=4.2.0 doorkeeper=3.0.0
  - rails=4.1.0 doorkeeper=4.2.0
  - rails=4.2.0 doorkeeper=4.2.0

gemfile:
  - gemfiles/Gemfile.mongoid2.rb
  - gemfiles/Gemfile.mongoid3.rb
  - gemfiles/Gemfile.mongoid4.rb
  - gemfiles/Gemfile.mongoid5.rb
  - gemfiles/Gemfile.mongo_mapper.rb

services:
  - mongodb

matrix:
  exclude:
    - env: rails=3.2.0 doorkeeper=3.0.0
      rvm: 2.2

    - env: rails=3.2.0 doorkeeper=4.2.0
      rvm: 2.2

    - env: rails=3.2.0 doorkeeper=3.0.0
      rvm: 2.3.1

    - env: rails=3.2.0 doorkeeper=4.2.0
      rvm: 2.3.1

    # mongoid 2
    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.1.0 doorkeeper=3.0.0

    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.2.0 doorkeeper=3.0.0

    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.1.0 doorkeeper=4.2.0

    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.2.0 doorkeeper=4.2.0
    # mongoid 3
    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.1.0 doorkeeper=3.0.0

    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.2.0 doorkeeper=3.0.0

    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.1.0 doorkeeper=4.2.0

    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.2.0 doorkeeper=4.2.0



    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: rails=3.2.0 doorkeeper=3.0.0
    - gemfile: gemfiles/Gemfile.mongoid5.rb
      env: rails=3.2.0 doorkeeper=3.0.0
